name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Build and Release Quarkus Backend
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Quarkus project
        working-directory: CalorieTrackerBackend
        run: ./gradlew build

      - name: Get current datetime for version
        id: get_datetime
        run: |
          datetime=$(date +"%Y%m%d%H%M%S")
          echo "::set-output name=version::$datetime"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build JVM Docker image
#        working-directory: CalorieTrackerBackend
#        run: |
#          docker build -f src/main/docker/Dockerfile.jvm -t ghcr.io/simon-b64/calorie-tracker-backend-jvm:${{ steps.get_datetime.outputs.version }} -t ghcr.io/simon-b64/calorie-tracker-backend-jvm:latest .
#          docker push ghcr.io/simon-b64/calorie-tracker-backend-jvm --all-tags

      - name: Build Native Docker image
        working-directory: CalorieTrackerBackend
        run: |
          docker build -f src/main/docker/Dockerfile.native -t ghcr.io/simon-b64/calorie-tracker-backend-native:${{ steps.get_datetime.outputs.version }} -t ghcr.io/simon-b64/calorie-tracker-backend-native:latest .
          docker push ghcr.io/${{ github.repository_owner }}/calorie-tracker-backend-native --all-tags
