name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Build and Release Quarkus Backend
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Quarkus project
        working-directory: CalorieTrackerBackend
        run: ./gradlew build

      - name: Extract version number
        id: extract_version
        working-directory: CalorieTrackerBackend
        run: echo "::set-output name=version::$(./gradlew properties -q | grep '^version:' | awk '{print $2}')"

      - name: Bump version number for release
        id: bump_version
        run: |
          old_version=${{ steps.extract_version.outputs.version }}
          new_version=$(echo "$old_version" | awk -F. '{$NF += 1; print $1 "." $2 "." $NF}')
          echo "::set-output name=new_version::$new_version"

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.new_version }}
          release_name: Release ${{ steps.bump_version.outputs.new_version }}
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload OpenAPI YAML to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: CalorieTrackerBackend/build/generated/openapi.yaml
          asset_name: openapi.yaml
          asset_content_type: application/yaml

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build JVM Docker image
        working-directory: CalorieTrackerBackend
        run: |
          docker build -f src/main/docker/Dockerfile.jvm -t ghcr.io/${{ github.repository_owner }}/calorie-tracker-backend-jvm:${{ steps.bump_version.outputs.new_version }} .
          docker push ghcr.io/${{ github.repository_owner }}/calorie-tracker-backend-jvm:${{ steps.bump_version.outputs.new_version }}

      - name: Build Native Docker image
        working-directory: CalorieTrackerBackend
        run: |
          docker build -f src/main/docker/Dockerfile.native -t ghcr.io/${{ github.repository_owner }}/calorie-tracker-backend-native:${{ steps.bump_version.outputs.new_version }} .
          docker push ghcr.io/${{ github.repository_owner }}/calorie-tracker-backend-native:${{ steps.bump_version.outputs.new_version }}
